name: fintrack

services:
  server:
    build:
      context: .
      target: dev
    image: fintrack-server
    container_name: fintrack-server
    working_dir: /workspace
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace
      - m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fintrack
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: frostbjorne
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: fintrack-db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fintrack"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  db-data:
  m2:

secrets:
  db-password:
    file: ./db/password.txt
